### PR TITLE
Add the Android app to /apk

### PR DESCRIPTION
**Pull request by Willow-Systems**
This PR adds the android app (com.getpebble.android.basalt) APK to a new directory, /apk

It's the APK taken from https://www.apkmirror.com/apk/pebble-technology-corp/pebble/pebble-4-4-2-1405-62d45d7d7-endframe-release/pebble-4-4-2-1405-62d45d7d7-endframe-android-apk-download/

I have also added an index page in /apk, so anyone visiting https://rebble.io/apk will see:

image

The button goes to rebble.io/apk/pebbleApp.apk, which downloads the APK

### CODE REVIEW

**Comment by ishotjr** [comment]
@Willow-Systems did you see my Discord comment yesterday? :bowtie: 

> ishotjr03/02/2021
APK might be best to put in a throwaway location
vs. on "actual" web site
that way takedown w/b decoupled

**Comment by Willow-Systems** [comment]
Okay, so we could put the apk on Google drive etc and point this page to that, or would you rather remove the whole page?

I think being able to point people to rebble.io/apk is useful, in the same way we have /discord or /charon

**Comment by ishotjr** [comment]
@Willow-Systems absolutely keep the page! The file could be in a different repo on GitHub, so that if we were asked to take it down, we could just nuke that repo, vs. for example tying it up in this site's Git history etc. :bowtie:

**Comment by Katharine** [comment]
Why not just put it on S3/GCS like all our other binary assets?

It really shouldn't be in any git repo. It isn't source code.

**Comment by ishotjr** [comment]
@Katharine great call! Aim was for it to be something simple, that we could all easily manage - GitHub seemed like an easy solution (vs. rando Google Drive link) - S3/GCS is even better - thanks for suggesting!!! 😍 👍

**Comment by Willow-Systems** [comment]
S3 makes sense! I have next to no AWS permissions, so if one of you can upload it and let me know the path, I'll update the page to point to it.

**Comment by Katharine** [comment]
Please squash these commits so the binary is not included in the commit history.

**Pull request merged**
