### PR TITLE
Close #46 new svg logos, add css and js that create a real-time clock.

### LINKED ISSUE #46: real-time clock SVG logo
I was thinking about converting logo SVG into a real-time clock. In plan is to change SVG directly with CSS and JS. If you are ok with that, I can try to do it (first time doing and not sure if it will succeed).

### PR DESCRIPTION
**Pull request by strdr4605**
screen shot 2018-07-14 at 18 22 15

### CODE REVIEW

**Comment by ishotjr** [comment]
@strdr4605 I believe @jneubrand created the original - I'm going to go ahead and push it as-is because I love it, but maybe you can work with him on an updated version? 💙

**Comment by droolface** [comment]
Hey guys on the topic of logos I'm not sure if you saw it on /r/pebble @ishotjr but I was tossing out a few ideas for (well, IMO) enhancing the Rebble logo to make the "Rebble" part more visibly associated with Pebble to help it sort of more directly _res ipsa loquitur_ what Rebble is all about (it's entirely based on the Pebble logo, reshuffling some bits to make the R).  I never had much of a chance to help out in other ways on the project so I thought maybe I could contribute in this small way if you guys like the idea.

It didn't get too much traction on the sub, and if you aren't keen on it no prob at all.  Just spent a few minutes throwing together some concepts with the plan to make usable versions if you decided to run with it.  It can totally coexist with the clock logo, it would just replace the "rebble" text (which could still be the alt-text for non-graphical browsers).

Here is the one I think had the most positive (least negative?) reception.  Let me know -- if you like it I could try to make up an SVG of it for actual use (obviously a heavy image would be bad for phone browsers, etc).

rebbleex_001

There was also a version that tried to punk it up a bit... but someone thought it reminded them of dickbutt so that might not be the intended effect.  =)

rebbleex_002

**Comment by ishotjr** [comment]
@droolface I like the notion of using pieces from the original logo - did you try lower case or was it just toooo similar/uninventive? I wonder if we could go further on other letters too? Can I get a link to the original thread too please? :metal: :bowtie: :metal:

**Comment by strdr4605** [comment]
@ishotjr I thought about the best solution. We need anyway 2 paths of arrows that are positioned 
screen shot 2018-07-20 at 14 29 34
I don't have the original file and it's hard for me to draw and calculate positions just from importing SVG in Illustrator.
After converting to SVG, the hard part begins. I need to find the point in the middle of the clock that will be the transform-origin of the arrows because in SVG origin is in the corner of the image, in this SVG the origin isn't at the corner of visible image but way to far from it, in a direction that even I am not sure. In the CSS I wrote 
```
.arrows {
  transform-origin: 64px 988px;
}
```
which is the most accurate position that I found for rotating arrows around their axis.
So your team can create a new SVG logo with 2 paths for arrows so I could manipulate each of them, I can try to find this origin.

**Comment by droolface** [comment]
Hey @ishotjr awesome, am pumped you don't totally hate the idea.  There was, at best, tepid reception on r/pebble... but people can be sometimes just be turds, especially on Reddit.  Here are two links... I deleted the first two ideas because they included part of the Star Wars rebel insignia and even with it 60% obscured people really strongly thought it would be a bad idea, and I didn't disagree.

* https://www.reddit.com/r/pebble/comments/8w1o77/rebble_logo_idea_3_the_same_as_2_without_the/
* https://www.reddit.com/r/pebble/comments/8w1sqv/rebble_logo_idea_4_since_people_seem_to_like_to/

These are super rough drafts I did in a few minutes one morning because the idea struck me when on rebble.io around the official launch.  I had figured that maybe the watch logo was kind of a beta/draft in terms of an official logo... mainly I was thinking that because it's impossible to tell what it is by looking at it, unless you already know and have really looked.  Seemed to me that if people saw it out of context who haven't been directly involved in the project... even Rebble users... wouldn't be able to place it (it's logo design best practice to make it self-evident).  *But* if you combine it with the word Rebble in a logo then it's cool.  Obviously a combined logo would be for use in places other than the top of the rebble.io site because of the cool working clock @strdr4605 has put together here... but just the word part can be used there and a static combined one can be used elsewhere.

So yeah, if you are into the idea I'll def spend a little time remaking it in Illustrator and coming up with some more variations if you like.  I admit I only signed into the Discord a few times because it's a little intense for me to have live chats etc going on.  I mean, sometimes in life you have to go see a man about a snake.

**Pull request merged**
