### PR TITLE
Add GNU AGPLv3 license

### PR DESCRIPTION
**Pull request by Avamander**

### CODE REVIEW

**Comment by jneubrand** [comment]
I'm ok with AGPL3 for all templates & styling I committed. However, I'm not sure whether content should be freely licensed... let's see what @ishotjr says about that :)

**Comment by jneubrand** [comment]
(That being said, I'd prefer permissive on styles and all rights reserved on content and especially the logo)

**Comment by Avamander** [comment]
Content can't be relicensed unless with explicit permission of the owner of the work. (That is not even needed this case)

**Comment by Avamander** [comment]
Graphical assets need a license meant for graphical works. That is another topic.

**Comment by jneubrand** [comment]
>Content (apps and other) can't be relicensed unless with explicit permission of the owner of the work.

...this is the rebble.io page, which contains no apps. I'm referring to blog posts, which is why I pinged ishotjr

>Graphical assets need a license meant for graphical works. That is another topic.

Yes, but agpl would apply unless you explicitly say it doesn't. See the first paragraph of the license:

> The GNU Affero General Public License is a free, copyleft license for software and **other kinds of works**, specifically designed to ensure cooperation with the community in the case of network server software.

(Relevant section emboldened.)

**Comment by Avamander** [comment]
I removed the () second before you commented. Though, I am aware of that AGPL also by default applies to graphical works, that's why I said they need their own license.

**Comment by jneubrand** [comment]
So, here are my thoughts:

- I'll talk to ishotjr and see what he thinks in terms of licensing.
- I'll probably put styles and templates under MIT?
- Graphics should probably be under a completely different license to avoid other projects tangentially related to pebble from copying them over without permission.

**Comment by Avamander** [comment]
Indeed, that sounds fine, I enabled contributor pushing to this branch so you can add the other licenses.

**Comment by ishotjr** [comment]
*closing in deference to https://github.com/pebble-dev/pebble-dev.github.io/pull/42* :bowtie:

**Pull request closed without merging**
