### PR TITLE
Direct users to auth to reset app boot config

### PR DESCRIPTION
**Pull request by MisterSpak**
The purpose of this PR is now just for the two changes that direct users to go to `auth.rebble.io` to reset their Pebble app config. For just all the other changes, see #52.

### CODE REVIEW

**Comment by ishotjr** [comment]
@MisterSpak this is great!  Would it be possible to break it into two PRs, one covering just the dependency on https://github.com/pebble-dev/rebble-auth-py/pull/7 (i.e. since that may take some time to put into production) and the other covering the rest? 😍 👍

**Comment by MisterSpak** [comment]
> @MisterSpak this is great! Would it be possible to break it into two PRs, one covering just the dependency on [pebble-dev/rebble-auth-py#7](https://github.com/pebble-dev/rebble-auth-py/pull/7) (i.e. since that may take some time to put into production) and the other covering the rest? 😍 👍

@ishotjr Done! I've created a new PR (#52) just for the changes that don't rely on updating `auth`.

**Comment by ishotjr** [comment]
@MisterSpak I had some [feedback](https://github.com/pebble-dev/pebble-dev.github.io/pull/52#pullrequestreview-229351981) that I'd love to incorporate into this (or another) PR when poss.... ❤️

**Comment by MisterSpak** [comment]
I kinda screwed up my `master` branch here so I'm just gonna close this.

**Pull request closed without merging**
