### PR TITLE
WIP: Refactor home page

### PR DESCRIPTION
**Pull request by sGerli**
Includes:
- New home page
- Moved common styles to modular SCSS

screenshot)

### CODE REVIEW

**Comment by sGerli** [comment]
Menu wrapping issues have been fixed with the las commit. Now I'm just waiting for feedback and text for the about section.

**Comment by ishotjr** [comment]
@sGerli this is really excellent!  I haven't done the "full" CR yet but I pulled and ran it locally and it looks great; only question I had is does it require #57 to be merged prior since I noticed that `/blog` doesn't actually work here?  I'll come up with some intro copy as part of the CR so we can get it all merged and live at once! 😍 🚀

**Comment by sGerli** [comment]
Yeah, it's better if #57 is merged first, so then we can rebase and fix the conflicts with this one and then merge. And that way we can prevent publishing unexisting links.

**Comment by ishotjr** [comment]
@sGerli cool - can you [fix the nav](https://github.com/pebble-dev/pebble-dev.github.io/pull/57/files#diff-5ff1a95f53423a31000317ea545a02a9R4) in #57 so that can be merged and deployed, ready for use here? ❤️ (alternately we could merge it with a different base to prevent deployment/the need for fixing the nav?)

**Comment by sGerli** [comment]
I could merge these two PRs if you want me to.

**Comment by ishotjr** [comment]
@sGerli literally `merge` or just "combine" for me to then review/approve/`merge`?  If the latter: that would be perfect! ❣️

**Comment by sGerli** [comment]
Combine by merging them into a third branch and then send you a PR.

**Comment by ishotjr** [comment]
@sGerli perfect! 🚀

**Comment by sGerli** [comment]
Superseded by #59

**Pull request closed without merging**
