### PR TITLE
Small updates to howto

### PR DESCRIPTION
**Pull request by ja-besse**

### CODE REVIEW

**Comment by ishotjr** [comment]
@ja-besse awesome! Working on a few things on the web site today and will check this out ASAP! :heart_eyes: :+1:

**Comment by ja-besse** [comment]
Did you have time to review this one already?

**Comment by ishotjr** [comment]
@ja-besse apologies! Will do this weekend!! :blue_heart:

**Comment by ja-besse** [comment]
While you're at it... ?

**Pull request merged**
